In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('train.csv')[['Age', 'Pclass', 'SibSp', 'Parch', 'Survived']]
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [3]:
df.shape

(891, 5)

In [4]:
df.dropna(inplace = True)

In [5]:
df.shape

(714, 5)

In [6]:
X = df.iloc[:, :4]
y = df.iloc[:, -1]

In [7]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [15]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring = 'accuracy', cv = 20)) # cv = 20 means we do cross validation 20 times

np.float64(0.6933333333333332)

# Applying Featrure Construction

In [16]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1 # here we do +1 why because that person itself if a member of family

In [18]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [22]:
X[X['Family_size'] > 3]

      Age  Pclass  SibSp  Parch  Family_size
7     2.0       3      3      1            5
13   39.0       3      1      5            7
16    2.0       3      4      1            6
24    8.0       3      3      1            5
25   38.0       3      1      5            7
..    ...     ...    ...    ...          ...
819  10.0       3      3      2            6
824   2.0       3      4      1            6
850   4.0       3      4      2            7
858  24.0       3      0      3            4
885  39.0       3      0      5            6

[78 rows x 5 columns]

In [23]:
(X['Family_size'] > 3).value_counts()

Family_size
False    636
True      78
Name: count, dtype: int64

In [27]:
def family_type(num):
    if num ==1:
        return 0 # alone
    elif num > 1 and num <=4:
        return 1 # Samll Family
    else:
        return 2 # Large Family

In [28]:
X['Family_type'] = X['Family_size'].apply(family_type)

In [29]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [30]:
X.drop(columns = ['SibSp', 'Parch', 'Family_size'], inplace = True)

In [31]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [35]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring = 'accuracy', cv = 20))

np.float64(0.7003174603174602)

# Feature Splitting

In [36]:
df1 = pd.read_csv('train.csv')
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [37]:
df1['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [44]:
df1['Title'] = df1['Name'].str.split(',',expand = True)[1].str.split('.', expand = True)[0]

In [45]:
df1[['Title','Name']]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]