In [1]:
import pandas as pd
import numpy as np

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working With Date

In [7]:
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1. Extract Year

### dt :- dt means DateTime

In [9]:
date['date_year'] = date['date'].dt.year

In [10]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

## 2. Extract Month

In [11]:
date['date_month'] = date['date'].dt.month

In [12]:
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

## 3. Month Name

In [13]:
date['date_month_name'] = date['date'].dt.month_name()

In [14]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

## 4. Extract Date

In [15]:
date['date_day'] = date['date'].dt.day

In [16]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

## 5. Day of Week

In [17]:
date['date_day_of_week'] = date['date'].dt.dayofweek

In [18]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

## 6. Day of week - name

In [19]:
date['date_dow_name'] = date['date'].dt.day_name()

In [20]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

## 7. Is weekend or not?

In [21]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Saturday','Sunday']),1,0)

In [22]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

## 8. Extract Quarter

In [23]:
date['date_quarter'] = date['date'].dt.quarter

In [24]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week,date_dow_name,date_is_weekend,date_quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

## 9. Extract semester

In [25]:
date['date_semester'] = np.where(date['date_quarter'].isin([1,2]), 1, 2)

In [26]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week,date_dow_name,date_is_weekend,date_quarter,date_semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

## 10. Extract Time elapsed between dates

In [28]:
date['date_week_of_year'] = date['date'].dt.week

AttributeError: 'DatetimeProperties' object has no attribute 'week'

In [29]:
date.

SyntaxError: invalid syntax (3909538178.py, line 1)

In [31]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 1, 6, 22, 57, 6, 136559)

In [32]:
today - date['date']

0     2219 days 22:57:06.136559
1     2701 days 22:57:06.136559
2     2632 days 22:57:06.136559
3     2334 days 22:57:06.136559
4     2557 days 22:57:06.136559
                 ...
995   2647 days 22:57:06.136559
996   2588 days 22:57:06.136559
997   2436 days 22:57:06.136559
998   2501 days 22:57:06.136559
999   2275 days 22:57:06.136559
Name: date, Length: 1000, dtype: timedelta64[ns]

In [35]:
(today - date['date']).dt.days

0      2219
1      2701
2      2632
3      2334
4      2557
       ...
995    2647
996    2588
997    2436
998    2501
999    2275
Name: date, Length: 1000, dtype: int64

# TIME

In [37]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

# Working with time

In [38]:
time['date'] = pd.to_datetime(time['date'])

In [39]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [40]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['second'] = time['date'].dt.second

In [41]:
time.head()

,date,msg,hour,min,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## Extract time part

In [42]:
time['time'] = time['date'].dt.time

In [43]:
time.head()

,date,msg,hour,min,second,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## Extract Time difference

In [44]:
today - time['date']

0     4405 days 22:07:06.136559
1     4269 days 23:17:06.136559
2     4755 days 22:36:06.136559
3     4057 days 22:26:06.136559
4     4454 days 23:46:06.136559
                 ...
995   5044 days 22:07:06.136559
996   4365 days 23:43:06.136559
997   4830 days 23:20:06.136559
998   4946 days 23:23:06.136559
999   4218 days 23:32:06.136559
Name: date, Length: 1000, dtype: timedelta64[ns]

## Time in seconds

In [48]:
(today - time['date']) / np.timedelta64(1, 's')

0      3.806716e+08
1      3.689254e+08
2      4.109134e+08
3      3.506056e+08
4      3.849112e+08
           ...
995    4.358812e+08
996    3.772214e+08
997    4.173960e+08
998    4.274186e+08
999    3.645199e+08
Name: date, Length: 1000, dtype: float64

## Time in Minutes

In [49]:
(today - time['date']) / np.timedelta64(1, 'm')

0      6.344527e+06
1      6.148757e+06
2      6.848556e+06
3      5.843426e+06
4      6.415186e+06
           ...
995    7.264687e+06
996    6.287023e+06
997    6.956600e+06
998    7.123643e+06
999    6.075332e+06
Name: date, Length: 1000, dtype: float64

## Time in hours

In [50]:
(today - time['date']) / np.timedelta64(1, 'h')

0      105742.118371
1      102479.285038
2      114142.601705
3       97390.435038
4      106919.768371
           ...
995    121078.118371
996    104783.718371
997    115943.335038
998    118727.385038
999    101255.535038
Name: date, Length: 1000, dtype: float64